### ISSUE TITLE
extraPadding - InfoListItem

### ISSUE THREAD

**Issue by dishantjaykasodhan-eaton** [etn-ccis/blui-react-native-component-library#377]
https://github.com/etn-ccis/blui-react-native-component-library/commit/e06f28ee6371e56bba86a4897943a4ce0b773fc4

extra padding added in above PR -> paddingleft:16, 

and there is already paddingHorizontal for main Content 
  mainContent: {
            flex: 1,
            paddingHorizontal: 16,
        },

**Comment by surajeaton** [comment]
@dishantjaykasodhan-eaton Can you please provide the code snippet you are using and use the template to report the bug, so that it is more understandable?

**Comment by dishantjaykasodhan-eaton** [comment]
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/132662650/d182152b-8cce-446a-b9d5-a1ff812f01af)


   <InfoListItem
        title={item.filterName}
        subtitle={item.filterType ?? ''}
        backgroundColor={AppColors.PRIMARY_WHITE_50}
        chevron
        hidePadding
        divider={'full'}
        onPress={() => {
          dispatch(setSelectedFilter(item));
          props.navigation.navigate(ROUTE_NAMES.FILTER_INFORMATION, {
            filterDetailData: item,
          });
        }}
      />
    );

**Comment by dishantjaykasodhan-eaton** [comment]
in previous version 
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/132662650/f5b6b2f0-e885-473c-bb2d-4f7cf74269f4)

**Comment by joebochill** [comment]
@dishantjaykasodhan-eaton This issue has been closed for not following our issue-reporting template. Please open a _new_ issue using the bug report template and provide all of the requisite information. Please pay special attention to the "Describe the bug/expected behavior" section — here is where you should clearly describe what the current behavior is and what you think the behavior **should** be — this is what will help us understand what exactly is the issue that you are reporting (instead of trying to guess from a screenshot). And when submitting code in the "Reproduction" section, please make sure you use code blocks so that the code is readable and ensure that your code snippet is a _minimum_ reproduction that we will actually be able to run (we should be able to drop it into any project and have it work)— if there is application specific code in your example, we won't be able to run it and we do not have the time available to clean up your code examples for you to get them to run.
