### ISSUE TITLE
status Stripe - InfoListItem

### ISSUE THREAD

**Issue by dishantjaykasodhan-eaton** [etn-ccis/blui-react-native-component-library#378]
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/132662650/2dbe3dae-85bb-4248-901c-f5e84395877c)

https://github.com/etn-ccis/blui-react-native-component-library/commit/91c2486af39c62eacddf40a00195403f33d91c4e

In above PR we have updated the root style, 
and we taking statusStripe as 'absolute' Position

should provide same height to statusStripe ->        

 minHeight: isWrapEnabled ? (props.dense ? 52 : 72) * fontScale : 'auto',
 height: !isWrapEnabled ? (props.dense ? 52 : 72) * fontScale : 'auto',

**Comment by surajeaton** [comment]
@dishantjaykasodhan-eaton Can you please provide the code snippet you are using and use the template to report the bug, so that it is more understandable?

**Comment by dishantjaykasodhan-eaton** [comment]
<InfoListItem
        title={item.event}
        subtitle={formatDate(item.date, DateFormats.dateAndTime)}
        backgroundColor={AppColors.PRIMARY_WHITE_50}
        hidePadding
        divider={'full'}
        chevron
        onPress={() =>
          props.navigation.navigate(ROUTE_NAMES.ALERT_DETAILS, {
            alertData: item,
            isActiveAlert,
          })
        }
        statusColor={
          isActiveAlert
            ? getstatus(item.severity)[0]
            : AppColors.PRIMARY_WHITE_50
        }
        style={{marginTop: isActiveAlert ? 8 : 0}} />

![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/132662650/2668510c-0395-4ed3-933b-2085ed32d20d)

**Comment by joebochill** [comment]
@dishantjaykasodhan-eaton This issue has been closed for not following our issue-reporting template. Please open a _new_ issue using the bug report template and provide all of the requisite information. Please pay special attention to the "Describe the bug/expected behavior" section — here is where you should clearly describe what the current behavior is and what you think the behavior **should** be — this is what will help us understand what exactly is the issue that you are reporting (instead of trying to guess from a screenshot). And when submitting code in the "Reproduction" section, please make sure you use code blocks so that the code is readable and ensure that your code snippet is a _minimum_ reproduction that we will actually be able to run (we should be able to drop it into any project and have it work)— if there is application specific code in your example, we won't be able to run it and we do not have the time available to clean up your code examples for you to get them to run.
