### ISSUE TITLE
Dark theme Mobile Stepper, the "active" color should be primary

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-native-component-library#474]
## Describe the bug / expected behavior

Current Dev:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/dd541b30-3b27-4913-ac0b-8cd80e49bbab)
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/12074e3f-1e5b-41b6-baa5-f3889b7f725a)

Design:
![image](https://github.com/etn-ccis/blui-react-native-component-library/assets/8997218/05334fd8-daf4-4f66-b8d4-91012b5eb749)

## Suggested fix

Use the `primary` color from the theme

## Anything else to add?
Remember to modify readme and JSDoc if necessary

**Comment by huayunh** [comment]
This issue was marked as complete but did not address the logged issue: https://github.com/etn-ccis/blui-react-native-showcase-demo/issues/150

**Comment by ektaghag-eaton** [comment]
The issue https://github.com/etn-ccis/blui-react-native-showcase-demo/issues/150 got merged after recording the video. Will recheck and close it.

**Comment by ektaghag-eaton** [comment]
BLUI-5066

**Comment by ektaghag-eaton** [comment]
Hi @huayunh, this issue is fixed. Please check the screenshot and check the background color prop on top of every image.

Progress bar with primary color 
<img width="386" alt="Screenshot 2023-12-26 at 6 26 49 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/133877691/03ee96b3-bb72-4a78-8786-d053027eccf6">

Dot inactive color in dark theme
<img width="388" alt="Screenshot 2023-12-26 at 6 25 55 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/133877691/7bf26177-f04e-4d89-b53d-f429322ad9b7">

Dot Active color in dark theme
<img width="393" alt="Screenshot 2023-12-26 at 6 25 41 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/133877691/2d13a03d-d91f-4e02-baab-8522cbef5a76">

Dot Inactive color light theme
<img width="400" alt="Screenshot 2023-12-26 at 6 25 15 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/133877691/c4bf7d37-6a72-4aba-baf1-7db50e798b7d">

Dot Active color in light theme
<img width="392" alt="Screenshot 2023-12-26 at 6 24 55 PM" src="https://github.com/etn-ccis/blui-react-native-showcase-demo/assets/133877691/bbd49502-7b1a-478a-91e1-fed0ea10c3c9">
